# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"instance_sort": "02_explore.ipynb",
         "instance_dcmread": "02_explore.ipynb",
         "instance_show": "02_explore.ipynb",
         "get_dicom_image": "02_explore.ipynb"}

modules = ["explore.py"]

doc_url = "https://asvcode.github.io/test_fmi/"

git_url = "https://github.com/asvcode/test_fmi/tree/master/"

def custom_doc_links(name): return None
