# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_one.ipynb (unless otherwise specified).

__all__ = []

# Cell
from fastai.vision.all import *
from fastai.medical.imaging import *
from torchvision.utils import save_image
matplotlib.rcParams['image.cmap'] = 'bone'